// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SHMDemo.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SHMDemo.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

SHMDemo::SHMDemo()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2fd66ad3
    m_index = 0;
    // m_message com.eprosima.idl.parser.typecode.StringTypeCode@5d11346a
    m_message ="";
    // m_time com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7a36aefa
    m_time = 0;

}

SHMDemo::~SHMDemo()
{



}

SHMDemo::SHMDemo(
        const SHMDemo& x)
{
    m_index = x.m_index;
    m_message = x.m_message;
    m_time = x.m_time;
}

SHMDemo::SHMDemo(
        SHMDemo&& x)
{
    m_index = x.m_index;
    m_message = std::move(x.m_message);
    m_time = x.m_time;
}

SHMDemo& SHMDemo::operator =(
        const SHMDemo& x)
{

    m_index = x.m_index;
    m_message = x.m_message;
    m_time = x.m_time;

    return *this;
}

SHMDemo& SHMDemo::operator =(
        SHMDemo&& x)
{

    m_index = x.m_index;
    m_message = std::move(x.m_message);
    m_time = x.m_time;

    return *this;
}

bool SHMDemo::operator ==(
        const SHMDemo& x) const
{

    return (m_index == x.m_index && m_message == x.m_message && m_time == x.m_time);
}

bool SHMDemo::operator !=(
        const SHMDemo& x) const
{
    return !(*this == x);
}

size_t SHMDemo::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 1024*20 + 1;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t SHMDemo::getCdrSerializedSize(
        const SHMDemo& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.message().size() + 1;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void SHMDemo::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_message;
    scdr << m_time;

}

void SHMDemo::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_message;
    dcdr >> m_time;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void SHMDemo::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t SHMDemo::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& SHMDemo::index()
{
    return m_index;
}

/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void SHMDemo::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void SHMDemo::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& SHMDemo::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& SHMDemo::message()
{
    return m_message;
}
/*!
 * @brief This function sets a value in member time
 * @param _time New value for member time
 */
void SHMDemo::time(
        int64_t _time)
{
    m_time = _time;
}

/*!
 * @brief This function returns the value of member time
 * @return Value of member time
 */
int64_t SHMDemo::time() const
{
    return m_time;
}

/*!
 * @brief This function returns a reference to member time
 * @return Reference to member time
 */
int64_t& SHMDemo::time()
{
    return m_time;
}


size_t SHMDemo::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool SHMDemo::isKeyDefined()
{
    return false;
}

void SHMDemo::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
